### ISSUE TITLE
Ionos - Ubnt 18.04

### ISSUE THREAD

**Issue by anon11012019** [Domain-Connect/DomainConnectDDNS-Python#17]
I cannot get Ubuntu 18.04 to recognize DynDNS. I keep getting an error, "domain-connect-dyndns: command not found" when running the command per instructions from this repo: "domain-connect-dyndns --domain website.com setup"

Can you point me in the right direction?

**Comment by pawel-kow** [comment]
Hi, there is a help article at IONOS about the needed installation steps for Ubuntu:
https://www.ionos.com/help/domains/configuring-your-ip-address/connecting-a-domain-to-a-network-with-a-changing-ip-using-dynamic-dns-linux/

**Comment by pawel-kow** [comment]
Issue stalled. Closing.
