### ISSUE TITLE
Token Expiration after long phase of unchanged IP

### ISSUE THREAD

**Issue by Disco1267** [Domain-Connect/DomainConnectDDNS-Python#24]
Hi ! 
I am experiencing an issue in this particular situation:
An IP update fails with this message:

>Cannot get async token: Failed to read from https://api.domainconnect.1and1.com/v2/oauth/access_token?client_id=domainconnect.org&client_secret=inconceivable&grant_type=refresh_token&redirect_uri=https%3A%2F%2Fdynamicdns.domainconnect.org%2Fddnscode&refresh_token=xxxxxxxxxxx. HTTP code: 400
Could not update DNS record.

I suspect that the refresh token has expired. And the reason would be that the IP didn't change over a long period of time:
Last IP update was 2019-12-02
Next IP update was supposed to happen on: 2020-02-21
That's more than 3 monthes.

So how can I avoid this? Is there a way to enforce an update token. 

Thanks for any help

**Comment by pawel-kow** [comment]
Hi @Disco1267 
we'll take a look into that, to have some minimum update interval to prevent refresh_tokens from expire.
For the time being, as a workaround, you may re-setup your domain and add a second entry to your cron to run the script every 2 weeks with `--ignore-previous-ip` option, which will enforce the update even if no IP change is detected.

**Comment by Disco1267** [comment]
I will do that. Thank you.
Just one more question: For how long is the refresh token valid?

**Comment by pawel-kow** [comment]
@Disco1267, it's 30 days at IONOS.

**Comment by Disco1267** [comment]
Thanks again!

**Comment by pawel-kow** [comment]
Re-opening, as actually code still needs to be fixed

**Comment by pawel-kow** [comment]
Fixed with d01c06f961da60b3f429583afd7399760f296e86
Will be released with v0.0.7
