### ISSUE TITLE
How I can setup a A-Record for a wildcard subdomain

### ISSUE THREAD

**Issue by mkb79** [Domain-Connect/DomainConnectDDNS-Python#26]
Thank you for your good work!

I have a domain at ionos.de who supports domain connect.

For the domain I have two A-Records. One for the root domain and one for the wildcard domain „*“!

I can setup and change the A-Record for the root domain with your python module. But how I can do this for the wildcard domain?

Best regards 

mkb79

**Comment by pawel-kow** [comment]
@mkb79 I'm afraid Domain Connect specification does not allow for working with wildcards, it would make conflict detection almost impossible or at least very complex. Sorry for that.
Maybe for such advanced use-case it would be better to go over API to change DNS?

**Comment by mkb79** [comment]
Thanks for your fast reply.
