### ISSUE TITLE
Cannot get async token

### ISSUE THREAD

**Issue by mawa1105** [Domain-Connect/DomainConnectDDNS-Python#29]
Hey,
some days ago, the service stoped working!

I got this error when updating the A record manualy.

Cannot get async token: Failed to read from https://api.domainconnect.1and1.com/v2/oauth/access_token?client_id=domainconnect.org&client_secret=inconceivable&grant_type=refresh_token&redirect_uri=https%3A%2F%2Fdynamicdns.domainconnect.org%2Fddnscode&refresh_token=MTLKq9tYZYh3yeeFAXQepiyzogdApxs1GHoJ2CG19qI. HTTP code: 400

What can i do? I reinstalled everything. If i install the domain by using  domain-connect-dyndns setup --domain blabla.com it works for one time! 

Kind regard
M

**Comment by pawel-kow** [comment]
Hi, please post your settings.txt file before and after setup and then after the run fails. 
Please comment out the access token and refresh token and the domain name, so that it is not available for everyone in this post.

**Comment by mawa1105** [comment]
Hey thank you for the quick response,
where can I find the settings.txt?

M

**Comment by mawa1105** [comment]
Ok,
I found it (/root/dyndns/)!

I uninstalled domain-connect-dyndns it by using:
pip uninstall domain-connect-dyndns
and I renamed the settings.txt to settings.txt_old

Then I reinstalled it by using:
pip install domain-connect-dyndns

After that ther is no new settings.txt

Then I set it up by using:
domain-connect-dyndns setup --domain my.domain.com

I got the acces code and enterd it.
Still no settings.txt

i updated it by using:
domain-connect-dyndns update --all
It successfully updated the DNS record.
Still no settings.txt

Then I reconected my router (several times) and tryed it again and it seems to work.
Now I can find the settings.txt in the /root/ folder instead of /root/dyndns/ 
(Linux Armbian Buster)

Now everything seems to work!

Thanks for helping! :-)

**Comment by pawel-kow** [comment]
@mawa1105 , very good that it works now.
Please note that by default settings.txt is created/read from the folder in which you run `domain-connect-dyndns` command.
You can control the location of the file by specifying `--config <filename [with path]>` parameter

**Comment by mawa1105** [comment]
Ah, perfect hint! 
Thank you!
