### ISSUE TITLE
Unable to install on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by MgFrobozz** [Domain-Connect/DomainConnectDDNS-Python#36]
I attempted installing with pip and got a warning that python 3.4 is needed:

`$ pip install domain-connect-dyndns
validators requires Python '>=3.4' but the running Python is 2.7.17`

/usr/bin/python is currently symlinked to python2.7, and if I change that link, other apps break. 
I attempted installing with pip3 and got a seg fault:

`$ pip3 install domain-connect-dyndns
Collecting domain-connect-dyndns
Collecting validators>=0.12.6 (from domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/41/4a/3360ff3cf2b4a1b9721ac1fbff5f84663f41047d9874b3aa1ac82e862c44/validators-0.18.1-py3-none-any.whl
Collecting domain-connect>=0.0.7 (from domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/61/5d/2d85ec830ff8b814cbd9ba073f60f81789e457acfda3020e78f916facc53/domain_connect-0.0.7-py2.py3-none-any.whl
Collecting dnspython>=1.15.0 (from domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/90/49/cb426577c28ca3e35332815b795a99e467523843fc83cc85ca0d6be2515a/dnspython-2.0.0-py3-none-any.whl
Collecting requests>=2.21.0 (from domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/45/1e/0c169c6a5381e241ba7404532c16a21d86ab872c9bed8bdcd4c423954103/requests-2.24.0-py2.py3-none-any.whl
Collecting decorator>=3.4.0 (from validators>=0.12.6->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Collecting six>=1.4.0 (from validators>=0.12.6->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting future>=0.18.1 (from domain-connect>=0.0.7->domain-connect-dyndns)
Collecting cryptography>=2.8 (from domain-connect>=0.0.7->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/43/2e/8d2de0d73d177184bc9a15137cd9aae46c1b3a59842b5fde30c8b80a5b4e/cryptography-3.1-cp35-abi3-manylinux1_x86_64.whl
Collecting publicsuffix>=1.1.0 (from domain-connect>=0.0.7->domain-connect-dyndns)
Collecting publicsuffixlist>=0.6.11 (from domain-connect>=0.0.7->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/1c/6a/9a673550e255591bd61daf412dc148d7878069a62145312af2cb14eee114/publicsuffixlist-0.7.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.21.0->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.21.0->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/9f/f0/a391d1463ebb1b233795cabfc0ef38d3db4442339de68f847026199e69d7/urllib3-1.25.10-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests>=2.21.0->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests>=2.21.0->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting cffi!=1.11.3,>=1.8 (from cryptography>=2.8->domain-connect>=0.0.7->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/82/7e/9cc46f072c9a414b5a6e08c5c2da5db3bff2601e69c4a6d4f6a34e6f9cfc/cffi-1.14.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=2.8->domain-connect>=0.0.7->domain-connect-dyndns)
  Using cached https://files.pythonhosted.org/packages/ae/e7/d9c3a176ca4b02024debf82342dab36efadfc5776f9c8db077e8f6e71821/pycparser-2.20-py2.py3-none-any.whl
Installing collected packages: decorator, six, validators, future, pycparser, cffi, cryptography, dnspython, publicsuffix, publicsuffixlist, domain-connect, certifi, urllib3, idna, chardet, requests, domain-connect-dyndns
Successfully installed certifi-2020.6.20 cffi-1.14.2 chardet-3.0.4 cryptography-3.1 decorator-4.4.2 dnspython-2.0.0 domain-connect-0.0.7 domain-connect-dyndns-0.0.8 future-0.18.2 idna-2.10 publicsuffix-1.1.1 publicsuffixlist-0.7.4 pycparser-2.20 requests-2.24.0 six-1.15.0 urllib3-1.25.10 validators-0.18.1
Segmentation fault (core dumped)`

In dmesg:
`[Wed Sep  9 08:04:47 2020] pip3[27171]: segfault at a9 ip 000000000059c3e4 sp 00007ffd102433b8 error 4 in python3.6[400000+3b4000]`

**Comment by MgFrobozz** [comment]
Worked around this with 

`sudo -H python3 -m pip install domain-connect-dyndns`

**Comment by pawel-kow** [comment]
Hi, I could not reproduce the issue with python3. Both on root and on non root user with virtualenv.

For python 2.7 one needs to install the last version still supporting python 2.7 as for some reason pip is not selecting it automatically.
`pip install validators==0.14.2`
