### ISSUE TITLE
No Domain Connect config found for domain

### ISSUE THREAD

**Issue by DATKTV** [Domain-Connect/DomainConnectDDNS-Python#37]
Until yesterday everything worked fine. But today when I try to setup a domain this error is raised:

Traceback (most recent call last):
  File "/home/haproxyuser/.local/lib/python3.6/site-packages/dyndns/domain_setup.py", line 16, in main
    config = dc.get_domain_config(domain)
  File "/home/haproxyuser/.local/lib/python3.6/site-packages/domainconnect/domainconnect.py", line 245, in get_domain_config
    ret = self._get_domain_config_for_root(domain_root, domain_connect_api)
  File "/home/haproxyuser/.local/lib/python3.6/site-packages/domainconnect/domainconnect.py", line 271, in _get_domain_config_for_root
    raise NoDomainConnectSettingsException('No Domain Connect config found for {}.'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectSettingsException: No Domain Connect config found for my.domain

I tried to solve it with issue #33 and #35 but it didn't help.

Do you have an idea, what is wrong?

**Comment by mkb79** [comment]
I had the same issue since yesterday. Nothing helps. Tried multiple times to make a new setup. Since 1 hour all working fine for now. It seems the where some problems on provider side.

**Comment by pawel-kow** [comment]
Yes, the API was not available for few hours at IONOS. All back online now.

**Comment by DATKTV** [comment]
I still get the same error when trying to set a domain

Has it to be a txt or a cname record? 🤔

**Comment by pawel-kow** [comment]
@DATKTV formally it is TXT record but at IONOS we use CNAME at another host (in the end it's the same).

Here the valid output
```
root@localhost:~# dig TXT _domainconnect.connect.domains

; <<>> DiG 9.10.3-P4-Ubuntu <<>> TXT _domainconnect.connect.domains
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 61629
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_domainconnect.connect.domains.        IN      TXT

;; ANSWER SECTION:
_domainconnect.connect.domains. 3506 IN CNAME   _domainconnect.1and1.com.
_domainconnect.1and1.com. 26    IN      TXT     "api.domainconnect.1and1.com"

```

**Comment by DATKTV** [comment]
This is my output. Aside from the line > ` _domainconnect.1and1.com. 26    IN      TXT     "api.domainconnect.1and1.com" ` it seems the same. But I don't know how to insert this line in ionos center
```
user@localhost:~$ dig TXT _domainconnect.datktv.de

; <<>> DiG 9.11.3-1ubuntu1.13-Ubuntu <<>> TXT _domainconnect.datktv.de
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25189
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;_domainconnect.datktv.de.      IN      TXT

;; ANSWER SECTION:
_domainconnect.datktv.de. 2531  IN      TXT     "_domainconnect.1and1.com"

```

**Comment by pawel-kow** [comment]
@DATKTV , so you have mixed the type and the content of the record.
Please set the CNAME on host _domainconnect and target _domainconnect.1and1.com.

**Comment by DATKTV** [comment]
I already did this. Or is it wrong?
![cnameRecord](https://user-images.githubusercontent.com/38760174/93060120-fe83a880-f671-11ea-9a88-17a0c62e112a.PNG)

**Comment by pawel-kow** [comment]
@DATKTV now it's correct
You may now need few moments for the TTL so that the updated record will be resolved correctly.

**Comment by DATKTV** [comment]
@pawel-kow thank you very much. It works again 👍
