### ISSUE TITLE
HTTP 400 Failed to read after some days

### ISSUE THREAD

**Issue by MaxGitHubAccount** [Domain-Connect/DomainConnectDDNS-Python#39]
Hi all,

first of all thank you for this tool. It's very useful to automatically update the server's ip for my ionos domains.

Since I use it however I have the problem, that various dns entries cannot be set after a short period of time. I have a cronjob which runs every minute as specified in the tutorial at ionos on my lxc debian container on a debian server.

I created a bunch of DNS-Entries in the settings file 10+ and after some days some of them start to fail and are not set anymore.
When I manually run the update I see that for those I get the following response:

Cannot get async token: Failed to read from https://api.domainconnect.1and1.com/                                                                             v2/oauth/access_token?client_id=domainconnect.org&client_secret=inconceivable&gr                                                                             ant_type=refresh_token&redirect_uri=https%3A%2F%2Fdynamicdns.domainconnect.org%2                                                                             Fddnscode&refresh_token=MTKzDUuyxWta0-wT04EqZHbzoH2WMP_y7E2JQg7Wedw. HTTP code:                                                                              400
Could not update DNS records.

I can see that the last time I updated the settings file it was 3 days ago, when all updates ran through, so I guess that it's not the expiring issue as here: https://github.com/Domain-Connect/DomainConnectDDNS-Python/issues/24

Debian Buster 4.19.0-9-amd64
Python 3.7.3
Tutorial: https://www.ionos.de/hilfe/domains/ip-adresse-konfigurieren/domain-mittels-dynamischen-dns-mit-einem-netzwerk-mit-wechselnder-ip-verbinden-linux/

**Comment by pawel-kow** [comment]
Hi @MaxGitHubAccount ,
Seems there is some issue with refresh_token.
As this seems to be some specific issue at IONOS, not to the client software, please reach out to me via domain_connect_admin@domain.ionos.com so we can help to solve the issue. It might be related to some situation on your account, so better to handle it off github.

**Comment by pawel-kow** [comment]
Closing this issue for the record.

It is not advisable to run the tool in parallel for the same domains and config file, as it may render unpredictable race conditions on token exchange rendering valid new tokens being overwritten by old tokens.

**Comment by MaxGitHubAccount** [comment]
Thank you for the support!

**Comment by Varsius** [comment]
I have the exact same problem as @MaxGitHubAccount. Could you please share the solution you found in order to fix the problem?
@pawel-kow you recommended to use flock on linux systems (I am running an Ubuntu container on proxmox), could you please explain how to integrate flock in to the cronjobs described in this tutorial: https://www.ionos.de/hilfe/domains/ip-adresse-konfigurieren/domain-mittels-dynamischen-dns-mit-einem-netzwerk-mit-wechselnder-ip-verbinden-linux/ ?

**Comment by pawel-kow** [comment]
@Varsius sure. This is the configuration with flock I am using. Replace <path> with your actual path where the tool is installed in your system.
```
*/1 * * * * /usr/bin/flock -n /tmp/ipupdate.lck <path>/domain-connect-dyndns update --all
```

**Comment by pawel-kow** [comment]
for the record, help site has been also updated to follow the flock recommended usage
