### ISSUE TITLE
Cannot update my domain anymore -- Failed to resolve "example.de"

### ISSUE THREAD

**Issue by chrzimmer** [Domain-Connect/DomainConnectDDNS-Python#41]
Hello, unfortunately i cannot update my domains anymore. If i try this i get the following messages
Read whatever.example.de config.
  IP 99.00.93.72 found in A record
  Public IPv4 address: 99.00.93.118
Failed to resolve "example.de"
Could not update DNS records. 

I changed domainnames and IPs for security reasons
When i try to resolve example.de with nslookup, i works as expected.

I am not sure, but it could be that this behavior appeared after apt update && apt upgrade on my Ubuntu 18.04. 2 weeks ago. In the meantime (after noticing the error) i did an update to domain-connect-dyndns 0.0.8 but that changed nothing.

If i try to setup a new domain with "domain-connect-dyndns setup" (after removing the old entry) i get the same behavior as with issue #32 .

Honestly i don't know where to look for this error. Is it my Ubuntu update ? Error on provider side (IONOS) ? 

Sorry, Iam completely lost with that and desperately need this service (like it is always with error reports :-) Cheers Chris

**Comment by chrzimmer** [comment]
I apologize for my entry. It was a configuration problem on my side.

**Comment by chrzimmer** [comment]
issue closed

**Comment by pawel-kow** [comment]
Thanks!
