### ISSUE TITLE
Settings.txt written at default location (instead of specified)

### ISSUE THREAD

**Issue by pawel-kow** [Domain-Connect/DomainConnectDDNS-Python#44]
I've manually specified where the setting file is (in another folder), but when it runs it creates a new settings.txt in the home folder. I think it does this as it adds the last updated time. It would be good that when using the explicit flag for the setting folder, you then write back to this file

Oddly this behaviour does not happen when using the --ignore-previous-ip flag

As a workaround I just mv the new file to overwrite the original settings.txt. But this is not really ideal

_Originally posted by @liput in https://github.com/Domain-Connect/DomainConnectDDNS-Python/issues/18#issuecomment-806518553_

**Comment by pawel-kow** [comment]
@liput can you please check your version?
`pip show domain-connect-dyndns` ?

It looks like the issue you mention was fixed with 0.0.7.

**Comment by liput** [comment]
was on 0.0.6

have upgraded, thank

**Comment by pawel-kow** [comment]
Ok, thanks.
