### ISSUE TITLE
dynamicdns.domainconnect.org not reachable

### ISSUE THREAD

**Issue by DATKTV** [Domain-Connect/DomainConnectDDNS-Python#49]
Good evening,
when I try to enable my domain for dyndns with the `domain-connect-dyndns setup --domain <subdomain> --protocols ipv4 ipv6` command, ionos tries to redirect me to dynamicdns.domainconnect.org, but this address doesn't seem to work.

To make sure the problem is not unique to my end, I queried these two downdetectors, which also return a 'down':
[isitup.org](https://isitup.org/dynamicdns.domainconnect.org)
[downforeveryoneorjustme.com](https://downforeveryoneorjustme.com/dynamicdns.domainconnect.org)

Is the service down?

**Comment by pawel-kow** [comment]
Hi @DATKTV ,
Yes, we are aware and @benjaminbbowen is working to restore the service.
In the mean time you may use a workaround. When setting up a new domain, you may just copy the code query parameter from the browser URL to complete the process.

**Comment by benjaminbbowen** [comment]
I'm working to restore this service today. Will post here when it's available.

**Comment by DATKTV** [comment]
Thank you two very much 👍

**Comment by benjaminbbowen** [comment]
I think I restored this to a new server. Can you test this and let me know if anything is not working?

**Comment by Bilihh** [comment]
Hi there! Not working! It throws me a nginx 503 bad gateway error! 

> Hi @DATKTV ,
> Yes, we are aware and @benjaminbbowen is working to restore the service.
> In the mean time you may use a workaround. When setting up a new domain, you may just copy the code query parameter from the browser URL to complete the process.

This solution is not ideal but actually works

**Comment by DATKTV** [comment]
> I think I restored this to a new server. Can you test this and let me know if anything is not working?

For me it was working fine, after you said I should test ist. Sorry I didn't respond earlier

**Comment by ImadeLak** [comment]
Hello !
Im' getting a 502 bad gateway error while trying to reach : https://dynamicdns.domainconnect.org/

Is the service down ?

Thank you

**Comment by HellUltimateGames** [comment]
It may be but have a look at this

> Hi @DATKTV ,
> Yes, we are aware and @benjaminbbowen is working to restore the service.
> In the mean time you may use a workaround. When setting up a new domain, you may just copy the code query parameter from the browser URL to complete the process.

**Comment by ImadeLak** [comment]
Thank you, it works now, but I know now what to do when it's not :)

**Comment by EBMBA** [comment]
Hi ! 

I've also a 502 bad gateway error while trying to reach : https://dynamicdns.domainconnect.org/

And my cron task doesn't work since the 8th of August. I've checked with https://isitup.org/dynamicdns.domainconnect.org and service seems down... Any help or information please ? 

Thanks

**Comment by pawel-kow** [comment]
Resolved again. Thanks for noticing.

**Comment by anquegi** [comment]
Hi @pawel-kow  I'm getting 502 bad gateway on accesing https://dynamicdns.domainconnect.org/

**Comment by pawel-kow** [comment]
As I see it's online again.
