### ISSUE TITLE
Trouble domain-connect-dyndns 0.0.9 / python 3.9 / proxmox V 7.0

### ISSUE THREAD

**Issue by geds3169** [Domain-Connect/DomainConnectDDNS-Python#51]
Hello,
I'm having trouble installing DomainConnectDDNS again. After reinstalling a new hypervisor on a new server. The version of python is 3.9. The error message is as follows when I use the following command:

domain-connect-dyndns setup --domain web-connectivity.fr

Error:

*** domain-connect-dyndns 0.0.9 ***

Traceback (most recent call last):
  File "/usr/local/bin/domain-connect-dyndns", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/dyndns/command_line.py", line 81, in main
    print(domain_setup.main(domain, protocols, settings))
  File "/usr/local/lib/python3.9/dist-packages/dyndns/domain_setup.py", line 19, in main
    config = dc.get_domain_config(domain)
  File "/usr/local/lib/python3.9/dist-packages/domainconnect/domainconnect.py", line 256, in get_domain_config
    ret = self._get_domain_config_for_root(domain_root, domain_connect_api)
  File "/usr/local/lib/python3.9/dist-packages/domainconnect/domainconnect.py", line 282, in _get_domain_config_for_root
    raise NoDomainConnectSettingsException('No Domain Connect config found for {}.'.format(domain_root))
domainconnect.domainconnect.NoDomainConnectSettingsException: No Domain Connect config found for web-connectivity.fr.

Domain name registration on Ionos:

![image](https://user-images.githubusercontent.com/28867314/129929729-13eef4f1-d9ef-479e-b44b-56fd0b4125f1.png)

thank you in advance for your help

**Comment by pawel-kow** [comment]
@geds3169 please restore your _domainconnect record to the original value
CNAME   _domainconnect.1and1.com.

**Comment by geds3169** [comment]
I do this right away Chef :)

What I don't understand is that it worked so far.

**Comment by geds3169** [comment]
This is correct for you ?

![image](https://user-images.githubusercontent.com/28867314/129932889-452b345a-78a6-48b5-816c-baf80a652a0d.png)

**Comment by pawel-kow** [comment]
@geds3169 , it worked as after the initial setup all the endpoints are stored in the client's `settings.txt` file, so the discovery is not needed anymore.
For the new setup it's needed again.

Now you've overwritten the `autodiscover` record. This will prevent automatic configuration of email clients. I suggest restoring this one.

To fix the `_domainconnect` record, you'd need to add a new CNAME (through the "Add" button on the top of the page) with host `_domainconnect` and the target `_domainconnect.1and1.com.`. It will also automatically ask to remove the wrong TXT record on `_domainconnect` host.

**Comment by geds3169** [comment]
I think this shot if it's good what do you think?

![image](https://user-images.githubusercontent.com/28867314/129935346-636755f8-ce4b-415d-b4f9-925923078bea.png)

**Comment by pawel-kow** [comment]
@geds3169 looks good.
It will start working as soon as your resolver forgets the old cached value. As per TTL setting it should be like 1h.

**Comment by geds3169** [comment]
It's good it's functional !, only one answer: 502 Bad Gateway for the code, which can be confusing for a new user. So I got the code from the mentioned url:
https://dynamicdns.domainconnect.org/ddnscode?code=XXXXXXXXXXXXXXXXXXXXXXX&state=null

For the new ones copy the equivalent of XXXX

Thank you for your help, you are always so efficient :)

**Comment by pawel-kow** [comment]
@geds3169 this one is fixed as well. Thanks for the info.
