### ISSUE TITLE
Documentation needed:  How-To: Wildcard Subdomains

### ISSUE THREAD

**Issue by dr-br** [Domain-Connect/DomainConnectDDNS-Python#52]
Which entries does  `domain-connect-dyndns` alter exactly at my DNS provider?  
Is it only the  
@-A-record ("TYP/HOSTNAME/WERT/SERVICE" : "A/@/123.456.78.90/Dynamic DNS")  
which is modified or is the  
wildcard-A-record ("TYP/HOSTNAME/WERT/SERVICE" : "A/*/123.456.78.90/-")  
or any other A-record modified as well?

Thanks a lot, i really appreciate the tool!
Best from/to Karlsruhe

**Comment by pawel-kow** [comment]
Hi @dr-br , the tool uses the following Domain Connect template  https://github.com/Domain-Connect/Templates/blob/master/domainconnect.org.dynamicdns-v2.json

Depending on the request parameters, it's setting up IPv4, IPv6 or both groups. IPv4 is the default.

In theory it should be possible to use `*` in the host parameter, however Domain Connect specification is not explicitly defining behaviors with `*` used in the host parameter it may be DNS-provider specific how it is supported.
The python library behind this tool is not supporting * in the hostname (or rather the public-suffix library used to split the host from domain root), so right now it's not possible to do the setup with this tool.
Alternative might be to CNAME * host to a dyndns subdomain.

**Comment by pawel-kow** [comment]
Closing as WONTFIX for now.

**Comment by dr-br** [comment]
Thanks for the explanation.
