### ISSUE TITLE
Domain Connect Dydns not working

### ISSUE THREAD

**Issue by ImadeLake** [Domain-Connect/DomainConnectDDNS-Python#53]
Hello,

It seems that D-C-D is not working anymore.
When I try to update my domains I got this error:

> domain-connect-dyndns update --all
*** domain-connect-dyndns 0.0.9 ***

Read exampledomain.com config.
  IP YY.YY.YY.YY found in A record
  Public IPv4 address: XX.XX.XX.XX
Failed to get async token: 400 invalid_request
Could not update DNS records.

Do you have any tips for that please ?

Regards

**Comment by pawel-kow** [comment]
Hi,
Hi frequent the tool is being run?
The typical issue is that if the tool is executed only after IP update then some providers may change IPs less frequent than 30 days rendering the refresh token expired.
The tool detects IP changes itself and only triggers the API if necessary, so it's OK to run it more frequently without any risk of flooding the API and being blocked.

**Comment by fubar2** [comment]
Mine broke. 
I stupidly fiddled a bit trying to see what was going on using the IONOS dashboard.
Big mistake. 
Much floundering later down many rabbit holes about the API key, I put down the dashboard and backed off in a non threating manner...
and came to my senses, and reran the installer.
`domain-connect-dyndns setup --domain foo.com`
Loaded the generated URL and got the key.
All good. 
Worked for me.

**Comment by lawa42** [comment]
I am wondering what the solution to the problem is. I am running the tool every 60 seconds. And it stopped working. I deleted the config and rerun the setup but no change. I always get 

> Failed to get async token: 400 invalid_request

**Comment by kikislater** [comment]
token is blacklisted, you need to regenerate one

```
domain-connect-dyndns remove --domain your.sub.domain
# edit settings.txt as this tool doesn't work correctly

domain-connect-dyndns setup --domain your.sub.domain
```

Additionnaly if still doesn't work remove your subdomain from ionos interface and restart from beginning : subdomain creation, generate config and token with this tool

**Comment by lawa42** [comment]
No doesn't help. Still the same error. I managed to update the IPV4 using curl and following the instructions on the ionos website but thats all.
