### ISSUE TITLE
Config and template location

### ISSUE THREAD

**Issue by geds3169** [Domain-Connect/DomainConnectDDNS-Python#54]
Hello Pawell,

After a while without problems, I recently had a problem with the automatic update of my IP address.

I would like to know where the configuration is supposed to be, I can't find it.

Moreover, by resuming the documentation via IONOS, the crontab does not seem to work, would there be an error, or am I at fault.

https://www.ionos.fr/assistance/domaines/configurer-des-adresses-ip/connecter-un-domaine-a-un-reseau-avec-changement-dip-en-utilisant-dynamic-dns-linux/

Sincerely Guilhem

**Comment by pawel-kow** [comment]
Hi @geds3169 ,

The configuration is by defult in the same folder as `domain-connect-dyndns` was executed, so by default the home directory of the user, the `settings.txt` file.
It may be overwritten to any other location using `--config` parameter.

The crontab example assumes the setup as the root user, thus the setting `--config /root/dyndns/settings.txt` with the config file location.

When automatic update worked before and does not work now, please provide the output of the tool to be able to help futher. Please do not publish `settings.txt` file -> it contains tokens which allow for IP updates, so shall be kept secret!
