### ISSUE TITLE
Compatibility with FreeBSD

### ISSUE THREAD

**Issue by geds3169** [Domain-Connect/DomainConnectDDNS-Python#56]
Hello Pawel,
i try to install Domain connect ddns to FreeBSD (Pfsense), but encountring some error when i want install:

missing limit.h

Missing ffi library (https://cffi.readthedocs.io/en/latest/) & (https://pypi.org/project/cffi/)

I have installed gcc10

If you can help, thank you by advance

**Comment by pawel-kow** [comment]
Hi, I'm sorry I don't have any experience with FreeBSD.
If you manage to figure it out by googling around or asking over StackExchange or ServerFault I would appreciate repotting back on this or a contribution to the README.

**Comment by geds3169** [comment]
Hi Pawel, I'll try to mount a VM with FreeBSD quickly (this will be my first time too), I'll do a test install and get back to you as soon as possible.

**Comment by geds3169** [comment]
<h1 align="center">
Install domain-connect-dyndns on FreeBSD
</h1>

## Install python3 & pip3

*Use sudo if you are not in root (not for all commands)*

---

**Check the version of FreeBSD**

```bash
freebsd-version
```

**Return**

```bash
12.3-release
```

---

**Check if python is installed**

```bash
which python
```

**Return the version of python**

```bash
python 3.9.X
```

***or***

```bash
python: Command not found
```

**or**

```bash
# empty
```

---

**Install python**

```bash
pkg install python3 # python 3.9.14
```

**Test**

```bash
python
```

**It work leave the terminal python**

```python
exit()
```

---

**Install pip**

```bash
 pkg install py39-pip # because i'm using python 3.9.x.x
```

**Test**

```bash
pip --version
```

**Return**

```bash
pip 22.2.2 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

---

---

**Create symbolic link python**

```bash
ln -s /usr/local/bin/python3.9 /usr/local/bin/python
```

**Test**

```bash
python --version
```

**Return**

```batch
Python 3.9.14
```

---

**Create symbolic link pip** *(only if pip --version doesn't work)*

```bash
ln -s /usr/local/bin/pip-3.9 /usr/local/bin/pip
```

**Test**

```bash
pip --version
```

**Return**

```bash
pip 22.2.2 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
```

---

**Upgrade pip**

```bash
pip install --upgrade pip
```

---

**Add pip install to PATH** *(no more adverstissment "Consider adding this directory ...")*

```bash
export PATH="$HOME/.local/bin:$PATH" >> ~/.bashrc
```

---

---

<h2 align="center">
Install the package cryptography python
</h2>

**At the time of writing, it seems (unless I am mistaken) that it is not possible to simply install the package, so you have to compile it yourself.**

*Doesn't work in FreeBSD 12.3*

```bash
pip install cryptography
```

---

<h2 align="center">
Solution Install the package cryptography python
</h2>

```bash
pkg install security/py-cryptography
```

---

<h2 align="center">
Install domain-connect-dyndns
</h2>

```bash
pip install domain-connect-dyndns
```

---

---

<h2 align="center">
Install & Configure domain-connect-dyndns
</h2>

**Install the client with pip**

```bash
pip install domain-connect-dyndns
```

**Add your domain**

```bash
domain-connect-dyndns setup --domain NAME_OF_THE_DOMAIN # example.com
```

1. Copy and paste the link that appears on your terminal into your browser;
  
2. Accept
  
3. Enjoy the registration success
  

**To update all domains**

```bash
domain-connect-dyndns update --all
```

**Return**

```bash
Read example.com config.
IP XX.XX.XX.XX found in A record  # your old public IP, if is registred
New IP: 217.160.25.20 # your new IP
A record up to date. # Success
```

**Update automaticly (dynamic public IP)**

You can use crontab, and a script to retrieve your public ip via a website.

**Comment by pawel-kow** [comment]
So in short, the missing element was `pkg install security/py-cryptography` ?

**Comment by geds3169** [comment]
yes only
