### ISSUE TITLE
Cannot get async token: Failed to read from https://api.domainconnect.ionos.com/v2/oauth/access_token

### ISSUE THREAD

**Issue by it-da-de** [Domain-Connect/DomainConnectDDNS-Python#62]
Hello, since 4 ours i got this message in my logfile:
Read ticket.it-da.de config.
  IP 109.250.181.xxx found in A record
  Public IP address: 46.142.179.xxx
Cannot get async token: Failed to read from https://api.domainconnect.ionos.com/v2/oauth/access_token?client_id=domainconnect.org&client_secret=inconceivable&grant_type=refresh_token&redirect_uri=https%3A%2F%2Fdynamicdns.domainconnect.org%2Fddnscode&refresh_token=[...]. HTTP code: 500
Could not update DNS records.
directly after a new connection from my dsl router. This is ugly, becouse I have many DNS Entrys and non of them are working anymore.

**Comment by mkb79** [comment]
Same here. Setup a new one are result in the same exception.

**Comment by it-da-de** [comment]
I try to update to the current version with git pull; python3 setup.py build ;python3 setup.py install
makes no difference

**Comment by mkb79** [comment]
> I try to update to the current version with git pull; python3 setup.py build ;python3 setup.py install
> makes no difference

The 500 error code indicates that this is a server side error. Maybe they have some server issues after an internal update (config mistake or something else). I'll try again in some hours. In the meantime I edited the DNS record manual to my current dynamic IP via the IONOS app. But I don’t want to do this after receiving a new IP again and again.

**Comment by pawel-kow** [comment]
@lpanatau-ionos do you want to take a look into that?

**Comment by pawel-kow** [comment]
> Hello, since 4 ours i got this message in my logfile: Read ticket.it-da.de config. IP 109.250.181.xxx found in A record Public IP address: 46.142.179.xxx Cannot get async token: Failed to read from [https://api.domainconnect.ionos.com/v2/oauth/access_token?client_id=domainconnect.org&client_secret=inconceivable&grant_type=refresh_token&redirect_uri=https%3A%2F%2Fdynamicdns.domainconnect.org%2Fddnscode&refresh_token=[...]]

@it-da-de I pinged some folks at IONOS. You may also want to contact their support to report the issue in an official way. As per other comments it is not related to the tool itself, but rather to their OAuth server
Also... not the best idea to post your refresh_token here (I redacted it in your comment meanwhile). It may be used by anyone to manipulate your domain. I would recommend to go to IONOS control panel and invalidate all tokens to avoid such misuse.

**Comment by it-da-de** [comment]
>... not the best idea to post your refresh_token here (I redacted it in your comment meanwhile). It may be used by anyone to manipulate your domain. I would recommend to go to IONOS control panel and invalidate all tokens to avoid such misuse.
you are right, I also disable currently this token for the domain and set the IP manual.

**Comment by lianapanatau-ionos** [comment]
The problem is fixed. The root cause was a connectivity issue with the OAuth server.

**Comment by it-da-de** [comment]
Thank you!
