### ISSUE TITLE
DYNDNS Domain Connect ERROR

### ISSUE THREAD

**Issue by victorcg03** [Domain-Connect/DomainConnectDDNS-Python#64]
When I try to connect my domain with the command "domain-connect-dyndns setup --domain domain.com" it returns the error "Domain doesn't support Domain Connect".
My domain provider is IONOS, and they only tell me that it must be a problem with my server, that they can't do anything, but I've reinstalled ubuntu, I've reinstalled python, pip and the dyndns domain connect, and it still doesn't work. It gives me the same problem with all my domains, until a few days ago it worked perfectly, and I have restored the default settings of all my domains, and it still doesn't work. And I don't know what else to do.

**Comment by pawel-kow** [comment]
Try 'dig TXT _domainconnect.domain.com' to check the setup of your domain.

**Comment by victorcg03** [comment]
> Try 'dig TXT _domainconnect.domain.com' to check the setup of your domain.

Where? I have my domain with IONOS.

**Comment by pawel-kow** [comment]
it's linux command line.
If you don't have it, please read here http://askubuntu.com/questions/25098/ddg#25100

**Comment by victorcg03** [comment]
> it's linux command line. If you don't have it, please read here http://askubuntu.com/questions/25098/ddg#25100

; <<>> DiG 9.18.12-0ubuntu0.22.04.2-Ubuntu <<>> TXT _domainconnect.victorcorral.                                                                                                                                                             com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 64512
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;_domainconnect.victorcorral.com. IN    TXT

;; Query time: 375 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Mon Jul 31 02:39:49 CEST 2023
;; MSG SIZE  rcvd: 60

**Comment by pawel-kow** [comment]
Report this to IONOS, why there is failed response.

**Comment by victorcg03** [comment]
What should I tell them? Do I send them the result of the command?

**Comment by victorcg03** [comment]
What should I tell them? Do I send them the result of the command as is?

**Comment by victorcg03** [comment]
What should I tell them? Do I send them the result of the command as is?

**Comment by pawel-kow** [comment]
Yes, SERVFAIL should not be happening

**Comment by victorcg03** [comment]
I sent them an email with the command output error, and they replied this:

----------

We have reviewed the _domainconnect value on your domains and it is currently set to a default value of IONOS.

"CNAME Host: _domainconnect - Value: _domainconnect.ionos.com "

If you want to use this CNAME for your custom configuration you will probably need to set a specific value that allows you to make this setting.

In this case, as it is a personalized configuration on your computer, we do not have information or support; In any case, I hope that this information provided will help you resolve your situation.

----------

What should i do now? What value do I put in the domain connect?

**Comment by X-Anonymous-Y** [comment]
> victorcorral.com

I have the same problem with IONOS. Have you found a solution? everything was running smoothly for me until a few days ago I noticed the same error "SERVFAIL" in the logs.

**Comment by X-Anonymous-Y** [comment]
> I sent them an email with the command output error, and they replied this:
> 
> We have reviewed the _domainconnect value on your domains and it is currently set to a default value of IONOS.
> 
> "CNAME Host: _domainconnect - Value: _domainconnect.ionos.com "
> 
> If you want to use this CNAME for your custom configuration you will probably need to set a specific value that allows you to make this setting.
> 
> In this case, as it is a personalized configuration on your computer, we do not have information or support; In any case, I hope that this information provided will help you resolve your situation.
> 
> What should i do now? What value do I put in the domain connect?

I have the same problem with IONOS. Have you found a solution? everything was running smoothly for me until a few days ago I noticed the same error "SERVFAIL" in the logs.

**Comment by pawel-kow** [comment]
I would say the same as previously - there is an issue with IONOS DNS servers.
So you should insist on the support line on the issue being passed to a 3rd level, as 1st level support apparently have no clue.

Alternatively you may try reaching out to hostmaster email listed in the SOA hostmaster@1und1.com.

**Comment by davidesteras** [comment]
> > I sent them an email with the command output error, and they replied this:
> > We have reviewed the _domainconnect value on your domains and it is currently set to a default value of IONOS.
> > "CNAME Host: _domainconnect - Value: _domainconnect.ionos.com "
> > If you want to use this CNAME for your custom configuration you will probably need to set a specific value that allows you to make this setting.
> > In this case, as it is a personalized configuration on your computer, we do not have information or support; In any case, I hope that this information provided will help you resolve your situation.
> > What should i do now? What value do I put in the domain connect?
> 
> I have the same problem with IONOS. Have you found a solution? everything was running smoothly for me until a few days ago I noticed the same error "SERVFAIL" in the logs.

I find a workaround to fix this, change CNAME entry of "_domainconnect" for "_domainconnect.1and1.com" instead of "_domainconnect.ionos.com" and it works!!!

I hope this can help.
