### ISSUE TITLE
Error: "Domain doesn't support Domain Connect."

### ISSUE THREAD

**Issue by Keks-Dose** [Domain-Connect/DomainConnectDDNS-Python#65]
We are on a Raspberry Pi, 
`lsb_release -d
Description:    Raspbian GNU/Linux 11 (bullseye)`

I installed domain-connect-dyndns:
```
pi@nextcloudpi:~ $sudo pip3 install domain-connect-dyndns
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting domain-connect-dyndns
  Using cached https://www.piwheels.org/simple/domain-connect-dyndns/domain_connect_dyndns-0.0.9-py3-none-any.whl (10 kB)
Requirement already satisfied: validators>=0.12.6 in /usr/local/lib/python3.9/dist-packages (from domain-connect-dyndns) (0.20.0)
Collecting domain-connect>=0.0.9
  Using cached https://www.piwheels.org/simple/domain-connect/domain_connect-0.0.9-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: requests>=2.21.0 in /usr/lib/python3/dist-packages (from domain-connect-dyndns) (2.25.1)
Requirement already satisfied: dnspython>=1.15.0 in /usr/lib/python3/dist-packages (from domain-connect-dyndns) (2.0.0)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from domain-connect>=0.0.9->domain-connect-dyndns) (1.16.0)
Requirement already satisfied: cryptography>=3.3.2 in /usr/lib/python3/dist-packages (from domain-connect>=0.0.9->domain-connect-dyndns) (3.3.2)
Collecting publicsuffixlist>=0.7.7
  Downloading https://www.piwheels.org/simple/publicsuffixlist/publicsuffixlist-0.10.0.20231002-py2.py3-none-any.whl (97 kB)
     |████████████████████████████████| 97 kB 1.2 MB/s 
Collecting future>=0.18.1
  Using cached https://www.piwheels.org/simple/future/future-0.18.3-py3-none-any.whl (492 kB)
Collecting publicsuffix>=1.1.0
  Using cached https://www.piwheels.org/simple/publicsuffix/publicsuffix-1.1.1-py3-none-any.whl (64 kB)
Collecting decorator>=3.4.0
  Using cached https://www.piwheels.org/simple/decorator/decorator-5.1.1-py3-none-any.whl (10 kB)
Installing collected packages: publicsuffixlist, publicsuffix, future, decorator, domain-connect, domain-connect-dyndns
Successfully installed decorator-5.1.1 domain-connect-0.0.9 domain-connect-dyndns-0.0.9 future-0.18.3 publicsuffix-1.1.1 publicsuffixlist-0.10.0.20231002
```

But:
```
pi@nextcloudpi:~ $sudo domain-connect-dyndns setup --domain yy.xxxx.de
*** domain-connect-dyndns 0.0.9 ***

Domain doesn't support Domain Connect.
```

It used to work for years. I called the host (ionos) and they can not find an issue on their side.

I've run out of ideas what to do.

**Comment by lawa42** [comment]
Same here. tried both a TXT as well as a CNAME record in the domain config.

Nothing works

**Comment by pawel-kow** [comment]
Sounds like an issue already reported by some folks in #64 
See [this comment](https://github.com/Domain-Connect/DomainConnectDDNS-Python/issues/64#issuecomment-1656956674) how to probe your DNS configuration if there is also SERVFAIL coming from IONOS.

**Comment by lawa42** [comment]
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 39423
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; _domainconnect.something.net.	IN	CNAME

;; ANSWER SECTION:
_domainconnect.something.net.	3600	IN	CNAME	_domainconnect.ionos.com.

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 226 msec
;; SERVER: 127.0.0.53
;; WHEN: Mon Oct 16 08:30:24 2023
;; MSG SIZE  rcvd: 83

**Comment by pawel-kow** [comment]
ok, then there must me something further down the line.

You may try this tool https://exampleservice.domainconnect.org/sync_index to see what is displayed.

If everything works fine this is an example output by IONOS:
![image](https://github.com/Domain-Connect/DomainConnectDDNS-Python/assets/28707030/f61c5b34-2d6d-49d7-b7a6-6be49a7ed3b6)

**Comment by davidesteras** [comment]
In case this could help:

https://github.com/Domain-Connect/DomainConnectDDNS-Python/issues/64#issuecomment-1764220863

**Comment by lawa42** [comment]
Changing the domain to 1and1.com as suggested by @davidesteras seems to help. Now also the doamin connect online tool suggested by @pawel-kow works. Before it just said that the domain does not support Domain connect.

Thanks

**Comment by lianapanatau-ionos** [comment]
Hi @lawa42. Now it should work with the CNAME record pointing to_domainconnect.ionos.com as well.

**Comment by pawel-kow** [comment]
Fixed I'd assume.

**Comment by lawa42** [comment]
Fixed indeed. Sorry for not following up. I had to change the DNS entry to 1and1.com as pointed out by @davidesteras
