### ISSUE TITLE
No Domain Connect config found for domain

### ISSUE THREAD

**Issue by rettungskoch** [Domain-Connect/DomainConnectDDNS-Python#66]
Hello,
I am a customer of IONOS. Probably since today I get the error "No Domain Connect config found for domain" when updating or creating a new domain.
I have not changed anything in my configuration. Does anyone have similar problems or has IONOS problems?

When I try the tool at https://exampleservice.domainconnect.org/sync_index, I get the following message:

"Manual change required.
The domain does not support domain connection. You need to make DNS changes manually.
Reason: No json returned for /settings"

**Comment by friendlyFella** [comment]
I have the same issue. It's probably and most likely their API borked again.

**Comment by pawel-kow** [comment]
```https://api.domainconnect.ionos.com/v2/it-da.de/settings``` returns error 500
@lianapanatau-ionos can you help? Aren't those endpoints monitored?

**Comment by lars-seelbach** [comment]
Hi, I got the same issue since yesterday. Would be very kind if we could get some help here :)
I had a quite disappointing call with the Ionos Service Hotline yesterday and was told, that there is no way to get any support from Ionos regarding this issue. Sorry, probably not the right place to complain about Ionos customer support. Just wanted to add a vote here, that any help is welcome!

**Comment by MarkusSchmitt22** [comment]
Hi @pawel-kow,  @rettungskoch and @loetermann 

thank you for reporting the issue with DomainConnect. The issue is already fixed and should be working as expected.

**Comment by rettungskoch** [comment]
hello @MarkusSchmitt22,
thank you for the feedback. i can confirm that everything works as expected.

**Comment by rettungskoch** [comment]
hello @MarkusSchmitt22,
thank you for the feedback. i can confirm that everything works as expected.

**Comment by it-da-de** [comment]
would be nice to get some of the problems background and if this will happen again.

**Comment by jjolmo** [comment]
Happens again, not sure if it's ideal to just create  a new thread. 2 of my 3 domains are failing. I had to set  up ip's manually. 
Where we should report these issues?

**Comment by pawel-kow** [comment]
@jjolmo assuming this is happening with IONOS I would first ask there why the tokens get invalidated. It might be a challenge to get through the 1st level support with such a specific question though. Usually they don't have too much clue of this.

**Comment by jjolmo** [comment]
> @jjolmo assuming this is happening with IONOS I would first ask there why the tokens get invalidated. It might be a challenge to get through the 1st level support with such a specific question though. Usually they don't have too much clue of this.

I'd prefer to find a paid alternative than having to pass through IONOS support. I also had troubles where the connections get invalidated too often (even when refreshing them with ignore-previous IP). This package served me so well for quite a bit time, but I cannot trust IONOS anymore for maintaining good uptime in the implementation.

Thanks!

**Comment by lianapanatau-ionos** [comment]
Hi @jjolmo! Let try to debug this. What domain names are you using?

**Comment by jjolmo** [comment]
> Hi @jjolmo! Let try to debug this. What domain names are you using?

Hi! I have dxlegends.com and crisistunidad.net 
both of them are failing. I created a setup for them multiple times. There should be something in the ionos side.
