### ISSUE TITLE
Issue updating dyndns of subdomains on ionos.de

### ISSUE THREAD

**Issue by Basti-Fantasti** [Domain-Connect/DomainConnectDDNS-Python#69]
I have setup two subdomains to be handled by the update script domain-connect-dyndns on my debian host.
It is set up to be run by flock as suggested.

Today I found out that one of the two domains has not been updated for quite a while.
The error I get is shown below.

I ran it manually several times, also using the --ignore-previous-ip setting but without success.

Here's the log:

```log
Read sub1.mydomain.de config.
  No A record found for domain  sub1.mydomain.de
  Public IPv4 address: 217.250.1.1
Failed to get async token: 400 invalid_request 
Could not update DNS records.

Read sub2.mydomain.de config.
  No A record found for domain sub2.mydomain.de
  Public IPv4 address: 217.250.1.1
Failed to get async token: 400 invalid_request 
Could not update DNS records.
```

strangly the sub2 domain is still working.

When looking up the history using the status flag I get the following:

```log
Domain: sub1.mydomain.de
IPv4 value: 217.250.1.3
Last DNS check: 17 June 2024 09:42
Last DNS failed update: 17 June 2024 09:42
Last DNS succesful update: 12 May 2024 09:55
Domain: sub2.mydomain.de
IPv4 value: 217.250.1.2
Last DNS check: 17 June 2024 09:42
Last DNS failed update: 17 June 2024 09:42
Last DNS succesful update: 06 January 2024 08:05
```

Do you have any idea why ionos is giving me an async token issue?

Thanks in advance

**Comment by pawel-kow** [comment]
Hi @Basti-Fantasti, this is vendor-specific problem so I won't be able to help directly.
Something worth trying would be to setup both domains anew to get new authorization and tokens.

**Comment by Basti-Fantasti** [comment]
Hi @pawel-kow thanks for your quick response.
Is there a way to get a more detailed debug logout when executing the script?

I'll also try as you have suggested to set up the domains from scratch.
Is there anything I need to clean up on the PC? Any temporary files?

**Comment by pawel-kow** [comment]
removing the `settings.txt` file should not be necessary, but in worst case worth trying.
I don't need additional debug to see that the token endpoint of IONOS answers with 400 on an attempt to token exchange.
Why this happens is beyond the client code.

**Comment by Basti-Fantasti** [comment]
@pawel-kow thanks again.
I just renamed the settings.txt file and added the domains again from scratch.
The domains have been successfully updated now.

Maybe my DSL provider keeps the same IP for quite a while so that no update is needed on the ionos side.
Do you think this could lead to the token being disabled or gone?

**Comment by pawel-kow** [comment]
the tool has a built in cycle for that to push updates and cycle tokens before expiry, at least as long as the tool is run often enough it should not be a problem.

**Comment by Basti-Fantasti** [comment]
Ok, thanks again. I'll keep an eye on it 👍
